apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-tester-go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-tester-go
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
